name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
#          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

#      - name: Detekt validation
#        run: ./gradlew detekt
